name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js 18.5.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.5.0
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build
        env:
          NEXT_PUBLIC_apiKey: "a variable"
          NEXT_PUBLIC_authDomain: "a variable"
          NEXT_PUBLIC_projectId: "a variable"
          NEXT_PUBLIC_storageBucket: "a variable"
          NEXT_PUBLIC_messagingSenderId: "a variable"
          NEXT_PUBLIC_appId: "a variable"
          NEXT_PUBLIC_measurementId: "a variable"
        run: yarn build
