name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 18.5.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.5.0
      - name: Install dependencies
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
